### ISSUE TITLE
i modified the code a bunch and for some reason i get an error like

### ISSUE THREAD

**Issue by LewisMCYoutube** [pavestnavi/weaselbot#1]
File "weaselbot.py", line 98
    "LewisMCYoutube--": ["LewisMCYoutube--"]
                     ^
SyntaxError: invalid syntax

**Comment by LewisMCYoutube** [comment]
aaaaaaaaaaaa

**Comment by LewisMCYoutube** [comment]
.,./,./p;]']'[;l,k

**Comment by LewisMCYoutube** [comment]
\dfegvthyjkilo;'#

**Comment by LewisMCYoutube** [comment]
fvgbhnjk,l.;p'[#'/;

**Comment by LewisMCYoutube** [comment]
dsa\AZSWEDRF

**Comment by LewisMCYoutube** [comment]
FVDSX;PP;

**Comment by LewisMCYoutube** [comment]
FVGBHYJKIJUHYTGHJKOLP;[']#']~

**Comment by pavestnavi** [comment]
Hello, sorry for the delay. I appreciate your help in reporting issues. The problem with this is that you're a fucking idiot who forgot to add a coma.

Have a good day, sir.

**Comment by LewisMCYoutube** [comment]
I
